"""
Deterministic SVG diagram generator for the patient explanation layer.

Renders a small left-to-right flow diagram (3-5 nodes):

    [What you told us] -> [Criterion matched] -> [Score contribution] -> [Result]

Driven DIRECTLY from the same rule-engine output already used for scoring
(the `breakdown` dict returned by calculate_wells_score /
calculate_centor_score). No LLM calls, no external images, no anatomy
artwork — pure programmatic SVG. Same input always produces byte-identical
output.
"""

from typing import List, Optional
from xml.sax.saxutils import escape

# Layout constants
_NODE_W = 210
_NODE_H = 84
_GAP = 48
_PAD = 20
_TITLE_H = 34

_NODE_FILL = "#f0f7ff"
_NODE_STROKE = "#2b6cb0"
_MATCH_FILL = "#e6ffed"
_MATCH_STROKE = "#2f855a"
_RESULT_FILL = "#fffbe6"
_RESULT_STROKE = "#b7791f"
_ARROW = "#4a5568"
_FONT = "font-family=\"Helvetica, Arial, sans-serif\""


def _wrap(text: str, width: int = 26, max_lines: int = 4) -> List[str]:
    """Greedy word wrap for node labels."""
    words = text.split()
    lines, cur = [], ""
    for w in words:
        if cur and len(cur) + 1 + len(w) > width:
            lines.append(cur)
            cur = w
        else:
            cur = f"{cur} {w}".strip()
    if cur:
        lines.append(cur)
    if len(lines) > max_lines:
        lines = lines[:max_lines]
        lines[-1] = lines[-1][: width - 1] + "\u2026"
    return lines


def _node(x: int, y: int, title: str, body: str, fill: str, stroke: str) -> str:
    parts = [
        f'<rect x="{x}" y="{y}" width="{_NODE_W}" height="{_NODE_H}" rx="10" '
        f'fill="{fill}" stroke="{stroke}" stroke-width="1.5"/>'
    ]
    parts.append(
        f'<text x="{x + _NODE_W // 2}" y="{y + 20}" text-anchor="middle" '
        f'{_FONT} font-size="12" font-weight="bold" fill="#1a202c">{escape(title)}</text>'
    )
    for i, line in enumerate(_wrap(body)):
        parts.append(
            f'<text x="{x + _NODE_W // 2}" y="{y + 38 + i * 14}" text-anchor="middle" '
            f'{_FONT} font-size="11" fill="#2d3748">{escape(line)}</text>'
        )
    return "".join(parts)


def _arrow(x1: int, y: int, x2: int) -> str:
    ay = y + _NODE_H // 2
    return (
        f'<line x1="{x1}" y1="{ay}" x2="{x2 - 8}" y2="{ay}" stroke="{_ARROW}" stroke-width="1.5"/>'
        f'<polygon points="{x2 - 8},{ay - 5} {x2},{ay} {x2 - 8},{ay + 5}" fill="{_ARROW}"/>'
    )


def generate_criterion_diagram(
    patient_words: str,
    criterion_label: str,
    criterion_matched: bool,
    points_contributed: object,
    total_score: int,
    tier: str,
    diagram_title: Optional[str] = None,
    match_text_override: Optional[str] = None,
) -> str:
    """Generate a deterministic 4-node SVG flow diagram for one criterion.

    Nodes: patient's words -> criterion match status -> score contribution
    -> overall result. All content comes from rule-engine output; nothing
    is generated by a model.

    Works for any rule-engine criterion with this shape, including Centor's
    (fever, absence of cough, tender cervical nodes, tonsillar exudate) as
    well as Wells'. `match_text_override` covers criteria that are not a
    simple present/absent boolean — e.g. Centor's McIsaac age modifier,
    which always applies and can contribute -1, 0, or +1 points rather than
    "matched" vs. "not matched".
    """
    n_nodes = 4
    width = _PAD * 2 + n_nodes * _NODE_W + (n_nodes - 1) * _GAP
    height = _PAD * 2 + _TITLE_H + _NODE_H
    y = _PAD + _TITLE_H

    if match_text_override is not None:
        match_text = match_text_override
        match_fill = _MATCH_FILL if criterion_matched else _NODE_FILL
        match_stroke = _MATCH_STROKE if criterion_matched else _NODE_STROKE
    else:
        match_text = ("Matched: counts toward the score"
                      if criterion_matched else "Not matched: does not count")
        match_fill = _MATCH_FILL if criterion_matched else _NODE_FILL
        match_stroke = _MATCH_STROKE if criterion_matched else _NODE_STROKE

    if isinstance(points_contributed, int):
        if points_contributed > 0:
            points_text = f"+{points_contributed} point" + ("s" if points_contributed != 1 else "")
        elif points_contributed < 0:
            points_text = f"{points_contributed} point" + ("s" if points_contributed != -1 else "")
        else:
            points_text = "0 points"
    else:
        points_text = str(points_contributed)

    title = diagram_title or f"How \u201c{criterion_label}\u201d affected your score"

    xs = [_PAD + i * (_NODE_W + _GAP) for i in range(n_nodes)]
    svg = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}">',
        f'<text x="{width // 2}" y="{_PAD + 10}" text-anchor="middle" {_FONT} '
        f'font-size="13" font-weight="bold" fill="#1a202c">{escape(title)}</text>',
        _node(xs[0], y, "What you told us", f"\u201c{patient_words}\u201d", _NODE_FILL, _NODE_STROKE),
        _arrow(xs[0] + _NODE_W, y, xs[1]),
        _node(xs[1], y, criterion_label, match_text, match_fill, match_stroke),
        _arrow(xs[1] + _NODE_W, y, xs[2]),
        _node(xs[2], y, "Score contribution", points_text, _NODE_FILL, _NODE_STROKE),
        _arrow(xs[2] + _NODE_W, y, xs[3]),
        _node(xs[3], y, "Result", f"Total score {total_score} \u2014 {tier} probability tier",
              _RESULT_FILL, _RESULT_STROKE),
        "</svg>",
    ]
    return "".join(svg)
